{% set version = '0.6.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatialsample
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatialsample_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatialsample/spatialsample_{{ version }}.tar.gz
  sha256: 201031bc89016abbcd268f044af4f00212268c0b8a0f6602980babe5ce6c8c7b

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cpp11
    - r-dplyr >=1.0.0
    - r-ggplot2
    - r-glue
    - r-purrr
    - r-rlang >=1.0.0
    - r-rsample >=1.1.1
    - r-sf >=1.0_9
    - r-tibble
    - r-tidyselect
    - r-units
    - r-vctrs >=0.3.6
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cpp11
    - r-dplyr >=1.0.0
    - r-ggplot2
    - r-glue
    - r-purrr
    - r-rlang >=1.0.0
    - r-rsample >=1.1.1
    - r-sf >=1.0_9
    - r-tibble
    - r-tidyselect
    - r-units
    - r-vctrs >=0.3.6

test:
  commands:
    - $R -e "library('spatialsample')"           # [not win]
    - "\"%R%\" -e \"library('spatialsample')\""  # [win]

about:
  home: https://spatialsample.tidymodels.org
  dev_url: https://github.com/tidymodels/spatialsample
  license: MIT
  summary: Functions and classes for spatial resampling to use with the 'rsample' package, such
    as spatial cross-validation (Brenning, 2012) <doi:10.1109/IGARSS.2012.6352393>.
    The scope of 'rsample' and 'spatialsample' is to provide the basic building blocks
    for creating and analyzing resamples of a spatial data set, but neither package
    includes functions for modeling or computing statistics. The resampled spatial data
    sets created by 'spatialsample' do not contain much overhead in memory.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: spatialsample
# Title: Spatial Resampling Infrastructure
# Version: 0.6.0
# Authors@R: c( person("Michael", "Mahoney", , "mike.mahoney.218@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2402-304X")), person("Julia", "Silge", , "julia.silge@posit.co", role = "aut", comment = c(ORCID = "0000-0002-3671-836X")), person(given = "Posit Software, PBC", role = c("cph", "fnd")) )
# Description: Functions and classes for spatial resampling to use with the 'rsample' package, such as spatial cross-validation (Brenning, 2012) <doi:10.1109/IGARSS.2012.6352393>. The scope of 'rsample' and 'spatialsample' is to provide the basic building blocks for creating and analyzing resamples of a spatial data set, but neither package includes functions for modeling or computing statistics. The resampled spatial data sets created by 'spatialsample' do not contain much overhead in memory.
# License: MIT + file LICENSE
# URL: https://github.com/tidymodels/spatialsample, https://spatialsample.tidymodels.org
# BugReports: https://github.com/tidymodels/spatialsample/issues
# Depends: R (>= 3.6)
# Imports: dplyr (>= 1.0.0), ggplot2, glue, purrr, rlang (>= 1.0.0), rsample (>= 1.1.1), sf (>= 1.0-9), stats, tibble, tidyselect, units, vctrs (>= 0.3.6)
# Suggests: covr, gifski, knitr, lwgeom, modeldata, rmarkdown, testthat (>= 3.0.0), tidyr, vdiffr, whisker, withr, yardstick
# LinkingTo: cpp11
# VignetteBuilder: knitr
# Config/Needs/website: tidyverse/tidytemplate
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.3.2
# NeedsCompilation: yes
# Packaged: 2024-10-02 16:48:50 UTC; mikemahoney218
# Author: Michael Mahoney [aut, cre] (<https://orcid.org/0000-0003-2402-304X>), Julia Silge [aut] (<https://orcid.org/0000-0002-3671-836X>), Posit Software, PBC [cph, fnd]
# Maintainer: Michael Mahoney <mike.mahoney.218@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-10-02 18:20:02 UTC
